# SPDX-License-Identifier: GPL-3.0-or-later
"""Built-in material styles.

A style is a pattern plus parameter values for the pattern ("surface"),
the weathering group ("finish") and optionally a detail overlay.
"""


class Style:
    def __init__(self, family, name, pattern, surface=None, finish=None,
                 detail=None, detail_values=None, size=1.0):
        self.family = family
        self.name = name
        self.pattern = pattern
        self.surface = surface or {}
        self.finish = finish or {}
        self.detail = detail or "NONE"
        self.detail_values = detail_values or {}
        self.surface.setdefault("Size", size)

    @property
    def id(self):
        return f"{self.family}/{self.name}"


FAMILIES = [
    ("BRICK", "Brick", "MOD_BUILD"),
    ("TILES", "Tiles", "MESH_GRID"),
    ("WOOD", "Wood", "OUTLINER_OB_FORCE_FIELD"),
    ("STONE", "Stone & Marble", "MATSPHERE"),
    ("CONCRETE", "Concrete & Asphalt", "MOD_REMESH"),
    ("METAL", "Metal", "SHADING_RENDERED"),
    ("ROOFING", "Roofing", "MOD_ARRAY"),
    ("GROUND", "Ground", "WORLD"),
    ("PLASTIC", "Plastic & Rubber", "META_BALL"),
    ("FABRIC", "Fabric & Leather", "MOD_CLOTH"),
    ("GLASS", "Glass, Water & Ice", "MOD_FLUIDSIM"),
    ("PAINT", "Paint, Plaster & Paper", "BRUSH_DATA"),
    ("ORGANIC", "Organic", "OUTLINER_OB_CURVES"),
]
FAMILY_LABEL = {k: n for k, n, _ in FAMILIES}

S = Style
STYLES = [
    # ---------------------------------------------------------------- brick
    S("BRICK", "Old Red Brick", "brick",
      {"Color A": "#7e3424", "Color B": "#a1543a", "Burnt Bricks": 0.18, "Grit": 0.7,
       "Mortar Color": "#a49d90", "Color Variation": 0.45},
      {"Dirt": 0.3, "Edge Wear": 0.2, "Wear Color": "#9a6a55", "Depth": 0.006}),
    S("BRICK", "London Stock", "brick",
      {"Color A": "#b8945c", "Color B": "#8f6d45", "Burnt Bricks": 0.25, "Grit": 0.8,
       "Mortar Color": "#b3aa98", "Color Variation": 0.5},
      {"Dirt": 0.45, "Grime Streaks": 0.3, "Depth": 0.006}),
    S("BRICK", "Modern Grey Brick", "brick",
      {"Color A": "#5c5a58", "Color B": "#6f6b67", "Burnt Bricks": 0.0, "Grit": 0.3,
       "Mortar Color": "#4a4846", "Color Variation": 0.2, "Mortar Width": 0.008, "Bevel": 0.002},
      {"Depth": 0.004}),
    S("BRICK", "White Painted Brick", "brick",
      {"Color A": "#e6e2da", "Color B": "#dcd7cd", "Burnt Bricks": 0.0, "Grit": 0.35,
       "Mortar Color": "#d9d4ca", "Color Variation": 0.08, "Roughness": 0.75},
      {"Edge Wear": 0.35, "Wear Color": "#8a4a35", "Dirt": 0.2, "Depth": 0.005}),
    S("BRICK", "Engineering Blue", "brick",
      {"Color A": "#2d2f33", "Color B": "#3d3a3c", "Burnt Bricks": 0.0, "Grit": 0.2,
       "Mortar Color": "#6c6862", "Color Variation": 0.25, "Roughness": 0.45}),
    S("BRICK", "Stack Bond", "brick",
      {"Bond Offset": 0.0, "Color A": "#8d4b37", "Color B": "#9b5b44", "Brick Length": 0.29,
       "Brick Height": 0.09, "Burnt Bricks": 0.05}),
    S("BRICK", "Mossy Garden Wall", "brick",
      {"Color A": "#6f3a2a", "Color B": "#86513b", "Burnt Bricks": 0.2, "Grit": 0.8,
       "Mortar Color": "#8f8a7c", "Color Variation": 0.5},
      {"Moss": 0.55, "Dirt": 0.5, "Edge Wear": 0.3, "Wear Color": "#8d6250", "Depth": 0.008}),
    S("BRICK", "Long Roman Brick", "brick",
      {"Brick Length": 0.5, "Brick Height": 0.04, "Color A": "#a69886", "Color B": "#8a7b6a",
       "Burnt Bricks": 0.0, "Mortar Color": "#c7bfb1", "Mortar Width": 0.012}),
    S("BRICK", "Cobblestone Setts", "brick",
      {"Brick Length": 0.15, "Brick Height": 0.1, "Mortar Width": 0.015, "Bevel": 0.02,
       "Color A": "#6e6a66", "Color B": "#55514d", "Burnt Bricks": 0.0, "Grit": 0.9,
       "Mortar Color": "#3a342c", "Mortar Depth": 0.8, "Color Variation": 0.6},
      {"Dirt": 0.5, "Moss": 0.15, "Depth": 0.02}),

    # ---------------------------------------------------------------- tiles
    S("TILES", "White Square Ceramic", "tiles",
      {"Tile Width": 0.15, "Tile Height": 0.15}),
    S("TILES", "Subway Tile", "tiles",
      {"Tile Width": 0.15, "Tile Height": 0.075, "Row Offset": 0.5, "Color A": "#f0eee8",
       "Bevel": 0.006, "Grout Color": "#c8c4bb", "Waviness": 0.35}),
    S("TILES", "Checker Floor", "tiles",
      {"Tile Width": 0.3, "Tile Height": 0.3, "Checker": 1.0, "Color A": "#ebe7de",
       "Color B": "#1d1d1f", "Roughness": 0.18, "Grout Width": 0.002}),
    S("TILES", "Terracotta Floor", "tiles",
      {"Tile Width": 0.3, "Tile Height": 0.3, "Color A": "#b25d38", "Color B": "#9a4a2b",
       "Color B Amount": 0.4, "Color Variation": 0.4, "Mottling": 0.5, "Grout Color": "#b9ae9a",
       "Grout Width": 0.01, "Roughness": 0.7, "Bevel": 0.006},
      {"Dirt": 0.25, "Edge Wear": 0.15}),
    S("TILES", "Large Format Stone", "tiles",
      {"Tile Width": 0.9, "Tile Height": 0.6, "Row Offset": 0.5, "Color A": "#b8b1a5",
       "Color Variation": 0.12, "Mottling": 0.6, "Grout Width": 0.003, "Roughness": 0.4}),
    S("TILES", "Blue Mosaic", "tiles",
      {"Tile Width": 0.025, "Tile Height": 0.025, "Grout Width": 0.002, "Color A": "#2f6da0",
       "Color B": "#5fa7c9", "Color B Amount": 0.45, "Color Variation": 0.5, "Roughness": 0.08,
       "Grout Color": "#dad7ce", "Bevel": 0.001}),
    S("TILES", "Green Glazed Zellige", "tiles",
      {"Tile Width": 0.1, "Tile Height": 0.1, "Color A": "#2f6b55", "Color Variation": 0.6,
       "Mottling": 0.5, "Waviness": 1.0, "Roughness": 0.06, "Grout Color": "#d8d2c4"}),
    S("TILES", "Concrete Pavers", "tiles",
      {"Tile Width": 0.4, "Tile Height": 0.4, "Row Offset": 0.5, "Color A": "#8e8b85",
       "Color Variation": 0.2, "Mottling": 0.7, "Grout Color": "#5b5650", "Grout Width": 0.006,
       "Roughness": 0.85, "Grout Depth": 0.6},
      {"Dirt": 0.4, "Moss": 0.15, "Depth": 0.01}),

    # ---------------------------------------------------------------- wood
    S("WOOD", "Oak Floorboards", "planks",
      {"Light Wood": "#c4975f", "Dark Wood": "#86592f", "Plank Width": 0.18}),
    S("WOOD", "Cathedral Oak", "planks",
      {"Light Wood": "#c9a06a", "Dark Wood": "#7d522b", "Plank Width": 0.22, "Plank Length": 2.2,
       "Figure": 1.2, "Ring Scale": 1.6, "Roughness": 0.3, "Coat": 0.3}),
    S("WOOD", "Walnut Floor", "planks",
      {"Light Wood": "#7a5236", "Dark Wood": "#3c2415", "Plank Width": 0.15, "Roughness": 0.35,
       "Plank Variation": 0.5}),
    S("WOOD", "Whitewashed Pine", "planks",
      {"Light Wood": "#e3d7c3", "Dark Wood": "#b49d7c", "Plank Width": 0.16, "Roughness": 0.7,
       "Plank Variation": 0.2}),
    S("WOOD", "Weathered Deck", "planks",
      {"Light Wood": "#8f8577", "Dark Wood": "#5a524a", "Plank Width": 0.14, "Gap": 0.006,
       "Plank Variation": 0.6, "Grain": 1.0, "Roughness": 0.85, "Stagger": 0.0},
      {"Dirt": 0.35, "Moss": 0.1, "Depth": 0.006}),
    S("WOOD", "Cedar Cladding", "planks",
      {"Light Wood": "#b5754a", "Dark Wood": "#7a4527", "Plank Width": 0.15, "Plank Length": 4.0,
       "Overlap": 1.0, "Gap": 0.0, "Roughness": 0.7}, {"Depth": 0.015}),
    S("WOOD", "Oak", "wood", {"Light Wood": "#c4975f", "Dark Wood": "#86592f"}),
    S("WOOD", "Walnut", "wood", {"Light Wood": "#6e4a31", "Dark Wood": "#33200f", "Roughness": 0.35}),
    S("WOOD", "Pine", "wood", {"Light Wood": "#e1c08e", "Dark Wood": "#b07a43", "Ring Scale": 2.0,
                               "Grain": 0.3}),
    S("WOOD", "Cherry", "wood", {"Light Wood": "#b86a40", "Dark Wood": "#6e2f18", "Grain": 0.5, "Figure": 1.0,
                                 "Roughness": 0.3, "Coat": 0.5}),
    S("WOOD", "Ebony", "wood", {"Light Wood": "#2a221d", "Dark Wood": "#0d0b0a", "Ring Scale": 0.5,
                                "Roughness": 0.25, "Coat": 0.6}),
    S("WOOD", "Birch Plywood", "wood", {"Light Wood": "#e4cfa8", "Dark Wood": "#c9a878", "Grain": 0.15,
                                        "Ring Scale": 3.0, "Figure": 0.3, "Roughness": 0.6}),
    S("WOOD", "Driftwood", "wood", {"Light Wood": "#a39b8f", "Dark Wood": "#6d665e", "Grain": 1.0,
                                    "Roughness": 0.9}, {"Edge Wear": 0.4, "Wear Color": "#c9c2b5"}),

    # ---------------------------------------------------------------- stone
    S("STONE", "Carrara Marble", "marble"),
    S("STONE", "Nero Marquina", "marble",
      {"Base Color": "#141414", "Cloud Color": "#252424", "Vein Color": "#d8d6d0",
       "Vein Width": 0.25}),
    S("STONE", "Calacatta Gold", "marble",
      {"Base Color": "#f1eee7", "Cloud Color": "#e2dccf", "Vein Color": "#9c7b4d",
       "Vein Width": 0.5, "Vein Scale": 0.8}),
    S("STONE", "Verde Guatemala", "marble",
      {"Base Color": "#1f3b2c", "Cloud Color": "#2f5a43", "Vein Color": "#c5d6c8",
       "Vein Width": 0.3, "Vein Scale": 2.5, "Secondary Veins": 1.0}),
    S("STONE", "Rosso Levanto", "marble",
      {"Base Color": "#5a2320", "Cloud Color": "#7a3a32", "Vein Color": "#d4c5b8",
       "Vein Width": 0.4, "Vein Scale": 2.0, "Vein Distortion": 12.0}),
    S("STONE", "Grey Granite", "speckle"),
    S("STONE", "Black Galaxy Granite", "speckle",
      {"Color A": "#151515", "Color B": "#050505", "Accent Color": "#c9a86b", "Dark Amount": 0.4,
       "Accent Amount": 0.04, "Grain Size": 0.003, "Polish": 0.95}),
    S("STONE", "Pink Granite", "speckle",
      {"Color A": "#b98a7a", "Color B": "#2c2726", "Accent Color": "#e8dfd8", "Dark Amount": 0.25,
       "Accent Amount": 0.25, "Grain Size": 0.006, "Polish": 0.5}),
    S("STONE", "Quartz Worktop", "speckle",
      {"Color A": "#ecebe8", "Color B": "#b8b5b0", "Accent Color": "#8d8a86", "Dark Amount": 0.2,
       "Accent Amount": 0.05, "Grain Size": 0.002, "Polish": 0.9}),
    S("STONE", "Sandstone", "strata"),
    S("STONE", "Limestone", "strata",
      {"Color A": "#d8cfbc", "Color B": "#c3b8a1", "Layer Scale": 4.0, "Pits": 0.5, "Grit": 0.3}),
    S("STONE", "Slate", "strata",
      {"Color A": "#454b52", "Color B": "#24282c", "Layer Scale": 40.0, "Layer Distortion": 3.0,
       "Grit": 0.5, "Pits": 0.0, "Roughness": 0.65}),
    S("STONE", "Travertine", "strata",
      {"Color A": "#e1d3b9", "Color B": "#c8b48f", "Layer Scale": 8.0, "Layer Distortion": 2.0,
       "Pits": 1.0, "Grit": 0.2, "Roughness": 0.5}),
    S("STONE", "Classic Terrazzo", "terrazzo"),
    S("STONE", "Dark Terrazzo", "terrazzo",
      {"Matrix Color": "#2f2f31", "Chip Color 1": "#d9d6cf", "Chip Color 2": "#8e8a84",
       "Chip Color 3": "#b08a5a"}),
    S("STONE", "Pastel Terrazzo", "terrazzo",
      {"Matrix Color": "#f2ece4", "Chip Color 1": "#e8a598", "Chip Color 2": "#9cc3c9",
       "Chip Color 3": "#e9cf8d", "Chip Size": 0.05, "Chip Density": 0.5}),

    # ---------------------------------------------------------------- concrete
    S("CONCRETE", "Smooth Concrete", "concrete"),
    S("CONCRETE", "Polished Concrete", "concrete",
      {"Color A": "#a3a19c", "Color B": "#8a8782", "Roughness": 0.25, "Pores": 0.15,
       "Aggregate": 0.2, "Stains": 0.1}),
    S("CONCRETE", "Weathered Concrete", "concrete",
      {"Color A": "#8d8b85", "Color B": "#6a6761", "Mottling": 0.9, "Pores": 0.6, "Stains": 0.7},
      {"Dirt": 0.5, "Grime Streaks": 0.6, "Moss": 0.1, "Depth": 0.005}),
    S("CONCRETE", "Exposed Aggregate", "concrete",
      {"Aggregate": 0.9, "Aggregate Size": 0.012, "Color A": "#8d877d", "Pores": 0.1},
      {"Depth": 0.008}),
    S("CONCRETE", "Fresh Asphalt", "concrete",
      {"Color A": "#232323", "Color B": "#1a1a1a", "Aggregate": 0.6, "Aggregate Size": 0.006,
       "Aggregate Color": "#6a6763", "Pores": 0.4, "Roughness": 0.9, "Stains": 0.0}),
    S("CONCRETE", "Worn Asphalt", "concrete",
      {"Color A": "#3d3d3c", "Color B": "#2c2c2b", "Aggregate": 0.8, "Aggregate Size": 0.008,
       "Aggregate Color": "#8a857e", "Pores": 0.6, "Roughness": 0.9, "Stains": 0.6},
      {"Dirt": 0.3, "Puddles": 0.3}),
    S("CONCRETE", "Cement Render", "concrete",
      {"Color A": "#b9b4aa", "Color B": "#a7a196", "Mottling": 0.3, "Pores": 0.1, "Stains": 0.3}),

    # ---------------------------------------------------------------- metal
    S("METAL", "Brushed Steel", "metal", {"Brushing": 1.0, "Roughness": 0.3}),
    S("METAL", "Polished Chrome", "metal", {"Color": "#e4e6e8", "Roughness": 0.04, "Variation": 0.05}),
    S("METAL", "Aluminium", "metal", {"Color": "#d4d6d8", "Roughness": 0.4, "Brushing": 0.3}),
    S("METAL", "Copper", "metal", {"Color": "#e08a62", "Roughness": 0.25, "Variation": 0.4}),
    S("METAL", "Aged Copper", "metal", {"Color": "#c27150", "Roughness": 0.45, "Variation": 0.6},
      {"Rust": 0.5, "Rust Color": "#4f8f7a", "Dirt": 0.3}),
    S("METAL", "Brass", "metal", {"Color": "#e2c06e", "Roughness": 0.25, "Variation": 0.3}),
    S("METAL", "Gold", "metal", {"Color": "#f5cd6a", "Roughness": 0.15, "Variation": 0.1}),
    S("METAL", "Galvanized Steel", "metal",
      {"Color": "#b7bbbd", "Roughness": 0.35, "Spangle": 1.0, "Spangle Size": 0.012}),
    S("METAL", "Cast Iron", "metal",
      {"Color": "#3b3a39", "Roughness": 0.7, "Hammered": 0.25, "Hammer Size": 0.004, "Variation": 0.5}),
    S("METAL", "Hammered Copper", "metal",
      {"Color": "#d2805a", "Roughness": 0.3, "Hammered": 1.0, "Hammer Size": 0.012}),
    S("METAL", "Rusted Steel", "metal", {"Color": "#5d5a57", "Roughness": 0.6, "Variation": 0.6},
      {"Rust": 0.75, "Dirt": 0.3, "Depth": 0.003}),
    S("METAL", "Painted Metal", "metal",
      {"Color": "#2f5d8a", "Metallic": 0.0, "Roughness": 0.35, "Variation": 0.1},
      {"Edge Wear": 0.4, "Wear Color": "#8a8b8c", "Wear Metallic": 1.0, "Wear Roughness": 0.35,
       "Rust": 0.15}),
    S("METAL", "Car Paint", "metal",
      {"Color": "#7a0e12", "Metallic": 0.0, "Roughness": 0.35, "Flakes": 0.7, "Coat": 1.0,
       "Variation": 0.0}),

    # ---------------------------------------------------------------- roofing
    S("ROOFING", "Spanish Barrel Tile", "roof_tiles",
      {"Barrel": 1.0, "Tile Width": 0.22, "Exposure": 0.35, "Row Offset": 0.0, "Gap": 0.0,
       "Color A": "#b25a34", "Color B": "#934126"}, {"Depth": 0.05, "Dirt": 0.3}),
    S("ROOFING", "Double Roman", "roof_tiles",
      {"Barrel": 0.6, "Tile Width": 0.15, "Exposure": 0.32, "Row Offset": 0.0, "Gap": 0.0,
       "Color A": "#8a4b37", "Color B": "#6e3a2b", "Roughness": 0.6}, {"Depth": 0.03, "Moss": 0.2}),
    S("ROOFING", "Plain Clay Tile", "roof_tiles",
      {"Tile Width": 0.165, "Exposure": 0.1, "Color A": "#9c4a2f", "Color B": "#7a3522"},
      {"Depth": 0.012, "Moss": 0.25, "Dirt": 0.3}),
    S("ROOFING", "Beaver Tail Tile", "roof_tiles",
      {"Tile Width": 0.18, "Exposure": 0.15, "Rounded Ends": 1.0, "Color A": "#a0472c",
       "Color B": "#81361f"}, {"Depth": 0.012}),
    S("ROOFING", "Natural Slate", "roof_tiles",
      {"Tile Width": 0.3, "Exposure": 0.22, "Color A": "#363b42", "Color B": "#2a2e33",
       "Color Variation": 0.3, "Roughness": 0.6, "Gap": 0.003}, {"Depth": 0.01}),
    S("ROOFING", "Asphalt Shingles", "roof_tiles",
      {"Tile Width": 0.33, "Exposure": 0.14, "Color A": "#3d3c3a", "Color B": "#2a2928",
       "Color Variation": 0.8, "Roughness": 0.9, "Gap": 0.006}, {"Depth": 0.008}),
    S("ROOFING", "Cedar Shakes", "roof_tiles",
      {"Tile Width": 0.16, "Exposure": 0.19, "Color A": "#8a6446", "Color B": "#5e4532",
       "Color Variation": 0.7, "Roughness": 0.85, "Gap": 0.008},
      {"Depth": 0.015, "Moss": 0.15}, detail="STRIPES",
      detail_values={"Detail Amount": 0.25, "Detail Size": 0.004, "Detail Color": "#3e2c1f"}),
    S("ROOFING", "Corrugated Iron", "sheet_roof", {"Pitch": 0.076, "Spangle": 0.5},
      {"Depth": 0.018, "Rust": 0.2}),
    S("ROOFING", "Box Rib Sheet", "sheet_roof",
      {"Pitch": 0.2, "Standing Seam": 1.0, "Seam Width": 0.05, "Minor Ribs": 0.5,
       "Color": "#3a4a52", "Metallic": 0.0, "Roughness": 0.4}, {"Depth": 0.03}),
    S("ROOFING", "Standing Seam Zinc", "sheet_roof",
      {"Pitch": 0.5, "Standing Seam": 1.0, "Seam Width": 0.02, "Color": "#8c9296",
       "Roughness": 0.5, "Spangle": 0.1}, {"Depth": 0.04}),

    # ---------------------------------------------------------------- ground
    S("GROUND", "Garden Soil", "ground", finish={"Depth": 0.012}),
    S("GROUND", "Gravel", "ground",
      {"Soil Color": "#4a4440", "Soil Color 2": "#3a3531", "Pebbles": 0.95, "Pebble Size": 0.02,
       "Pebble Color": "#9d958a", "Pebble Color 2": "#6a6560"}, {"Depth": 0.02}),
    S("GROUND", "River Pebbles", "ground",
      {"Soil Color": "#3a342e", "Pebbles": 1.0, "Pebble Size": 0.05, "Pebble Color": "#a8a092",
       "Pebble Color 2": "#5d5852", "Roughness": 0.6}, {"Depth": 0.04}),
    S("GROUND", "Beach Sand", "ground",
      {"Soil Color": "#d8c39b", "Soil Color 2": "#c4ab80", "Mottling": 0.3, "Pebbles": 0.03,
       "Pebble Size": 0.01, "Ripples": 0.8, "Ripple Spacing": 0.09, "Clumps": 0.1}, {"Depth": 0.012}),
    S("GROUND", "Desert Dunes", "ground",
      {"Soil Color": "#d39b5f", "Soil Color 2": "#b9824b", "Pebbles": 0.0, "Ripples": 1.0,
       "Ripple Spacing": 0.25, "Clumps": 0.05}, {"Depth": 0.012}),
    S("GROUND", "Mud", "ground",
      {"Soil Color": "#3d2f22", "Soil Color 2": "#2a2017", "Pebbles": 0.1, "Clumps": 0.8,
       "Roughness": 0.6}, {"Wetness": 0.6, "Puddles": 0.5}),
    S("GROUND", "Dry Grass", "ground",
      {"Soil Color": "#6b5b3f", "Grass": 0.8, "Grass Color": "#a39550", "Pebbles": 0.1}, {"Depth": 0.012}),
    S("GROUND", "Lawn", "ground",
      {"Soil Color": "#3c3020", "Grass": 1.0, "Grass Color": "#4a7a2a", "Pebbles": 0.0}, {"Depth": 0.012}),
    S("GROUND", "Forest Floor", "ground",
      {"Soil Color": "#4a3726", "Soil Color 2": "#2b1f15", "Pebbles": 0.15, "Grass": 0.3,
       "Grass Color": "#56632c"}, {"Moss": 0.3}, detail="SPOTS",
      detail_values={"Detail Amount": 0.5, "Detail Size": 0.06, "Detail Color": "#8a5a2a",
                     "Detail Depth": -0.3}),

    # ---------------------------------------------------------------- plastic
    S("PLASTIC", "Glossy Plastic", "plastic", {"Color": "#c8281e", "Roughness": 0.15}),
    S("PLASTIC", "Matte Plastic", "plastic", {"Color": "#e8e6e1", "Roughness": 0.6}),
    S("PLASTIC", "Textured ABS", "plastic", {"Color": "#2a2a2c", "Roughness": 0.45, "Texture": 1.0}),
    S("PLASTIC", "Rubber", "plastic", {"Color": "#151515", "Roughness": 0.85, "Texture": 0.3,
                                       "Texture Size": 0.0008}),
    S("PLASTIC", "Translucent Silicone", "plastic", {"Color": "#9ad1c9", "Roughness": 0.3,
                                                     "Subsurface": 1.0}),
    S("PLASTIC", "Wax", "plastic", {"Color": "#efe3c4", "Roughness": 0.4, "Subsurface": 1.0,
                                    "Color Variation": 0.2}),

    # ---------------------------------------------------------------- fabric
    S("FABRIC", "Linen", "fabric",
      {"Warp Color": "#cfc6b3", "Weft Color": "#bfb59f", "Thread Count": 15.0, "Fuzz": 0.6,
       "Thread Variation": 0.6, "Sheen": 0.3}),
    S("FABRIC", "Denim", "fabric",
      {"Warp Color": "#1c3a6b", "Weft Color": "#9eabc0", "Thread Count": 25.0, "Twill": 1.0,
       "Sheen": 0.1}),
    S("FABRIC", "Wool Tweed", "fabric",
      {"Warp Color": "#5a4a3a", "Weft Color": "#7a6d58", "Thread Count": 6.0, "Twill": 1.0,
       "Fuzz": 1.0, "Thread Variation": 0.9}),
    S("FABRIC", "Velvet", "fabric",
      {"Warp Color": "#5a0f22", "Weft Color": "#5a0f22", "Thread Count": 60.0, "Fuzz": 0.8,
       "Sheen": 1.0, "Roughness": 0.95}),
    S("FABRIC", "Canvas", "fabric",
      {"Warp Color": "#b8ab8c", "Weft Color": "#a99c7c", "Thread Count": 8.0, "Fuzz": 0.3}),
    S("FABRIC", "Brown Leather", "leather"),
    S("FABRIC", "Black Leather", "leather",
      {"Color": "#1a1817", "Crease Color": "#080707", "Roughness": 0.35, "Grain Depth": 0.4}),
    S("FABRIC", "Tan Suede", "leather",
      {"Color": "#a77a4f", "Crease Color": "#7d5a38", "Roughness": 0.95, "Sheen": 0.6,
       "Grain Size": 0.001}),

    # ---------------------------------------------------------------- glass
    S("GLASS", "Clear Glass", "glass"),
    S("GLASS", "Frosted Glass", "glass", {"Frost": 0.5}),
    S("GLASS", "Tinted Bottle Glass", "glass", {"Color": "#4a8a4a", "Roughness": 0.02, "Bubbles": 0.3}),
    S("GLASS", "Ruby", "glass", {"Color": "#b0102a", "IOR": 1.76}),
    S("GLASS", "Diamond", "glass", {"Color": "#ffffff", "IOR": 2.42}),
    S("GLASS", "Calm Water", "glass",
      {"Color": "#d6ebe8", "IOR": 1.333, "Ripples": 0.3, "Ripple Scale": 0.6}, {"Depth": 0.01}),
    S("GLASS", "Ocean Waves", "glass",
      {"Color": "#4a8aa0", "IOR": 1.333, "Ripples": 1.0, "Ripple Scale": 0.3}, {"Depth": 0.05}),
    S("GLASS", "Ice", "glass",
      {"Color": "#dff0f7", "IOR": 1.31, "Frost": 0.15, "Cracks": 0.8, "Bubbles": 0.4}),

    # ---------------------------------------------------------------- paint
    S("PAINT", "Smooth Plaster", "plaster"),
    S("PAINT", "Venetian Plaster", "plaster",
      {"Color": "#cdb89a", "Color 2": "#a88e6b", "Trowel": 1.0, "Roughness": 0.25,
       "Gloss Variation": 0.5}),
    S("PAINT", "Stucco", "plaster",
      {"Color": "#e9e1cf", "Color 2": "#d8cdb6", "Stucco": 0.8, "Stucco Size": 0.008, "Trowel": 0.2},
      {"Depth": 0.006, "Dirt": 0.2}),
    S("PAINT", "Painted Wall", "plaster",
      {"Color": "#e8e4dc", "Color 2": "#e2ddd3", "Trowel": 0.1, "Orange Peel": 0.6,
       "Roughness": 0.7}),
    S("PAINT", "Paper", "plaster",
      {"Color": "#f2efe6", "Color 2": "#e6e0d1", "Trowel": 0.2, "Fibers": 1.0, "Roughness": 0.9,
       "Orange Peel": 0.0}),
    S("PAINT", "Kraft Paper", "plaster",
      {"Color": "#b08b5b", "Color 2": "#9c7a4e", "Trowel": 0.3, "Fibers": 1.0, "Roughness": 0.9}),
    S("PAINT", "Peeling Paint", "plaster",
      {"Color": "#6d8f9a", "Color 2": "#5e7d88", "Trowel": 0.2},
      {"Edge Wear": 0.6, "Wear Color": "#b9b1a3", "Dirt": 0.35, "Depth": 0.003},
      detail="CRACKS", detail_values={"Detail Amount": 0.6, "Detail Size": 0.04,
                                      "Detail Color": "#c2baa8", "Detail Depth": 0.4}),

    # ---------------------------------------------------------------- organic
    S("ORGANIC", "Oak Bark", "bark"),
    S("ORGANIC", "Pine Bark", "bark",
      {"Color": "#6a4430", "Crevice Color": "#22150e", "Furrow Scale": 0.1, "Stretch": 2.0,
       "Flakiness": 1.0}),
    S("ORGANIC", "Birch Bark", "bark",
      {"Color": "#e6e1d8", "Crevice Color": "#2a2522", "Furrow Scale": 0.15, "Furrow Depth": 0.3,
       "Stretch": 0.25, "Flakiness": 0.2}),
    S("ORGANIC", "Skin Light", "skin"),
    S("ORGANIC", "Skin Medium", "skin", {"Color": "#b57f5e", "Blotch Color": "#9c5c44"}),
    S("ORGANIC", "Skin Dark", "skin", {"Color": "#6b4331", "Blotch Color": "#583224",
                                       "Roughness": 0.4}),
    S("ORGANIC", "Mossy Rock", "strata",
      {"Color A": "#6d6a64", "Color B": "#57544f", "Layer Scale": 3.0, "Grit": 0.8, "Pits": 0.5},
      {"Moss": 0.6, "Dirt": 0.4, "Depth": 0.01}),
    S("ORGANIC", "Snowy Rock", "strata",
      {"Color A": "#5d5a56", "Color B": "#45423f", "Layer Scale": 5.0, "Grit": 0.8},
      {"Snow": 0.6, "Depth": 0.01}),
]

STYLE_BY_ID = {s.id: s for s in STYLES}


def styles_in(family):
    return [s for s in STYLES if s.family == family]
