# SPDX-License-Identifier: GPL-3.0-or-later
"""Pre-rendered preview thumbnails.

Thumbnails live in the add-on's ``thumbs`` folder (generated by
``tools/render_thumbnails.py``). They are exposed two ways:

* as ``bpy.utils.previews`` icons for the sidebar's picture grid, and
* as GPU textures for the viewport dial.
"""

import os
import re

import bpy

THUMB_DIR = os.path.join(os.path.dirname(__file__), "thumbs")

_previews = None
_textures = {}


def file_key(key):
    """'BRICK/Old Red Brick' -> 'BRICK__Old_Red_Brick'"""
    return re.sub(r"[^A-Za-z0-9]+", "_", key.replace("/", "__")).strip("_")


def style_key(style_id):
    return style_id


def detail_key(detail):
    return f"DETAIL/{detail}"


def thumb_path(key):
    return os.path.join(THUMB_DIR, file_key(key) + ".png")


def has_thumb(key):
    return os.path.exists(thumb_path(key))


# -- sidebar icons -------------------------------------------------------------

def icon_id(key):
    """Preview icon id for a thumbnail, 0 if missing."""
    global _previews
    if _previews is None:
        import bpy.utils.previews
        _previews = bpy.utils.previews.new()
    if key in _previews:
        return _previews[key].icon_id
    path = thumb_path(key)
    if not os.path.exists(path):
        return 0
    return _previews.load(key, path, "IMAGE").icon_id


# -- GPU textures for the dial -----------------------------------------------------

def texture(key):
    """GPUTexture for a thumbnail (cached), or None when there is no file.

    Pixels are copied into a standalone texture and the temporary image
    datablock is removed straight away, so nothing ends up in the .blend and
    the texture survives file reloads.
    """
    if key in _textures:
        return _textures[key]
    tex = None
    path = thumb_path(key)
    if os.path.exists(path):
        import gpu
        import numpy as np
        img = bpy.data.images.load(path, check_existing=False)
        try:
            w, h = img.size
            px = np.empty(w * h * 4, dtype=np.float32)
            img.pixels.foreach_get(px)
            buf = gpu.types.Buffer("FLOAT", w * h * 4, px)
            tex = gpu.types.GPUTexture((w, h), format="RGBA16F", data=buf)
        finally:
            bpy.data.images.remove(img)
    _textures[key] = tex
    return tex


def clear():
    global _previews
    _textures.clear()
    if _previews is not None:
        import bpy.utils.previews
        bpy.utils.previews.remove(_previews)
        _previews = None
